name: Friend Link
description: Share your website with me :P
title: '[Friend Link]: '
labels: ['friend link']

body:
  - type: input
    attributes:
      label: 'URL of your website'
      placeholder: 'www.example.com'
    validations:
      required: true
  - type: input
    attributes:
      label: 'Your nickname, please?'
      placeholder: 'John Doe'
    validations:
      required: true
  - type: input
    attributes:
      label: 'Introduce yourself to others!'
      placeholder: '21 y.o. Front-End Developer from China...'
  - type: input
    attributes:
      label: 'Avatar URL'
      description: 'Your avatar will be fetched when building'
      placeholder: 'example.com/static/my_avatar.png'
