import '../styles/globals.css';
import { FC, ReactElement, ReactNode } from 'react';
import { createTheme, CssBaseline, ThemeProvider } from '@mui/material';
import Head from 'next/head';
import type { AppProps } from 'next/app';
import type { NextPage } from 'next';

import { AppLayout, DefaultLayout } from 'components/layout';

const theme = createTheme({
  palette: {
    primary: {
      main: '#2f4155',
    },
  },
  contentWidthScale: 0.95,
});

export type NextPageWithLayout = NextPage & {
  getLayout?: (page: ReactElement) => ReactNode;
};

interface AppWithLayoutProps extends AppProps {
  Component: NextPageWithLayout;
}

const MyApp: FC<AppWithLayoutProps> = ({ Component, pageProps }) => {
  return (
    <ThemeProvider theme={theme}>
      <CssBaseline />
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AppLayout>
        {Component.getLayout ? (
          Component.getLayout(<Component {...pageProps} />)
        ) : (
          <DefaultLayout>
            <Component {...pageProps} />
          </DefaultLayout>
        )}
      </AppLayout>
    </ThemeProvider>
  );
};

export default MyApp;
